### PR TITLE
bolding instead of linethrough playing title

### PR DESCRIPTION
**Pull request by jancborchardt**
Judging by the .alternative class it seems that the line-through is applied to tracks which are played from a source different than the original one. This is confusing and doesn’t really matter anyway as long as the track plays.

Instead, the currently playing track is now bolded additionally to better see it.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Did another change to not visually emphasize the play, prev, next buttons so much. Am not on my computer / OS atm, so had to add it to this pull request.

**Comment by jancborchardt** [comment]
And added some more. At the moment, Chrome does not recognize Youtify as having a search, this will help resolve that.

**Comment by pthulin** [comment]
Regarding the search field, the style looks fine in Firefox but messed up in Chrome (OS X).

Regarding the alternative class, it is used when a video is blocked and we start playing an alternative video. Hence the line-through.

The additional emphasis on currently playing track is nice.

**Comment by jancborchardt** [comment]
Hm, the style looks fine for me in Chrome OS. Can you take a screenshot? I fixed a small right padding error.

I understood that the alternative class is used when a video is blocked and the alternative is played. This, however, is not of interest to people if the end result is that the music is played. The linethrough seems as if the song is not available, yet it is. That’s why I removed it.

**Comment by kallux** [comment]
Sometimes the alternative search doesn't work and another totally unrelated video is played instead. That is why we need to emphasize that it is not the original video being played. Otherwise users might start to wonder why we messed up their playlists. 

I do agree that the strike through is too much and I think that maybe it's enough to put a small icon before the .title to indicate that an alternative is playing. Maybe a unicode char like ↹ or ↪. My vote is on the first one, but see if you can find something better at http://www.utf8-character.info/#!arrow

**Comment by pthulin** [comment]
Screenshot of searchbar on Chrome/Mac https://www.dropbox.com/s/kuc1qstsgptxwuf/searchbar.png

**Comment by kallux** [comment]
Added .alternative unicode char in dbce764dab. Also, I kind of like the somewhat tacky play/prev/next buttons with their large border. We'll think of a new design for the play/prev/next buttons when we redesign the whole bottom bar.

Creating a new issue for converting search type=input to type=search

**Pull request closed without merging**
